version: '2'
services:
  postgres:
    image: postgres

  omeroserver:
    image: openmicroscopy/omero-test-daemon-c7:0.2.0
    links:
      - postgres
    environment:
      - SKIP_UPGRADE_CHECK=true
    ports:
      - 4064:4064
      - 4063:4063

  test:
    build: ..
    links:
      - omeroserver
    volumes:
      - ../.:/home/omero/test
    command: /home/omero/test/docker/runtest
