version: '2'
services:
  postgres:
    image: postgres

  omeroserver:
    image: openmicroscopy/omero-test-daemon-c7:0.2.0
    links:
      - postgres
    environment:
      - SKIP_UPGRADE_CHECK=true
      - OMEROBUILD=${OMEROBUILD}
    ports:
      - 4064:4064
      - 4063:4063

  test:
    image: openmicroscopy/omero-test-daemon-c7:0.2.0
    links:
      - omeroserver
    environment:
      - SKIP_UPGRADE_CHECK=true
      - OMEROBUILD=${OMEROBUILD}
      - COMPONENT=server
      - RUNSCRIPT=py
      - SERVER_HOST=omeroserver
      - SERVER_PORT=4064
    volumes:
      - ../.:/home/omero/test
    command: /home/omero/test/docker/runtest
